lijunsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^results/', include('results.urls')),
    url(r'^admin/', admin.site.urls),
]

results/urls.py
from django.conf.urls import url

from . import views

app_name = 'results'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /consequence/5/
    url(r'^(?P<consequence_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /consequence/5/context/
    url(r'^(?P<consequence_id>[0-9]+)/context/$', views.context, name='context'),
    # ex: /results/mitigationindex/
    url(r'mitigationindex', views.mitigationindex, name='mitigationindex'),
    # ex: /consequence/5/mitigation/
    url(r'^(?P<consequence_id>[0-9]+)/mitigation/$', views.mitigation, name='mitigation'),
    # ex: /results/consequencelist/
    url(r'consequencelist', views.consequencelist, name='consequencelist'),
    # ex: /missinginfo/5/missingdetail/
    url(r'^(?P<missinginfo_id>[0-9]+)/missingdetail/$', views.missingdetail, name='missingdetail'),
    # ex: /missinginfo/5/manuallyaccept/
    url(r'^(?P<missinginfo_id>[0-9]+)/manuallyaccept/$', views.manuallyaccept, name='manuallyaccept'),
    # ex: /missinginfo/5/manualcommentsdetail/
    url(r'^(?P<missinginfo_id>[0-9]+)/manualcommentsdetail/$', views.manualcommentsdetail, name='manualcommentsdetail'),
    # ex: /missinginfo/5/addingdata/
    url(r'^(?P<missinginfo_id>[0-9]+)/addingdata/$', views.addingdata, name='addingdata'),
    # ex: /missinginfo/5/manualaddeddetail/
    url(r'^(?P<missinginfo_id>[0-9]+)/manualaddeddetail/$', views.manualaddeddetail, name='manualaddeddetail'),

]

results/models.py
from django.db import models

# Create your models here.
class Consequence(models.Model):
    consequence_text = models.CharField(max_length=20)
    def __str__(self):
        return self.consequence_text


class MissingInfo(models.Model):
    consequence = models.ForeignKey(Consequence, on_delete=models.CASCADE)
    missinginfo_text = models.CharField(max_length=200)
    def __str__(self):
        return self.missinginfo_text

class ManualComments(models.Model):
    consequence = models.ForeignKey(Consequence, on_delete=models.CASCADE)
    missinginfo_id = models.IntegerField(default=0)     
    missinginfo_text = models.CharField(max_length=200) 
    comments_text = models.CharField(max_length=200)
    operator = models.CharField(max_length=20)
    email = models.CharField(max_length=200)
    mod_date = models.DateTimeField('date modified')
    def __str__(self):
        return self.comments_text

class ManualAddInfo(models.Model):
    consequence = models.ForeignKey(Consequence, on_delete=models.CASCADE)
    missinginfo_id = models.IntegerField(default=0) 
    missinginfo_text = models.CharField(max_length=200)
    data = models.CharField(max_length=200)
    operator = models.CharField(max_length=20)
    email = models.CharField(max_length=200)
    mod_date = models.DateTimeField('date modified')
    def __str__(self):
        return self.data


class Likelihood(models.Model):
    consequence = models.ForeignKey(Consequence, on_delete=models.CASCADE)
    likelihood_text = models.CharField(max_length=20)
    def __str__(self):
        return self.likelihood_text


class Severity(models.Model):
    consequence = models.ForeignKey(Consequence, on_delete=models.CASCADE)
    severity_text = models.CharField(max_length=20)
    def __str__(self):
        return self.severity_text

results/forms.py
from django import forms

class ManuallyAcceptForm(forms.Form):
    comments = forms.CharField(widget=forms.Textarea)
    operator = forms.CharField(max_length=100)
    email = forms.EmailField()


class AddingDataForm(forms.Form):
    data = forms.CharField(max_length=200)
    operator = forms.CharField(max_length=100)
    email = forms.EmailField()
      

results/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect 

from .models import Consequence, MissingInfo, Likelihood, Severity, ManualComments, ManualAddInfo

from django.utils import timezone

from .forms import ManuallyAcceptForm, AddingDataForm

def index(request):
    consequence_list = Consequence.objects.all()
    context = {'consequence_list': consequence_list}
    return render(request, 'results/index.html', context)


def consequencelist(request):   
    consequence_list = Consequence.objects.all()
    context = {'consequence_list': consequence_list}
    return render(request, 'results/consequencelist.html', context) 


def mitigationindex(request):   
    consequence_list = Consequence.objects.all()
    context = {'consequence_list': consequence_list}
    return render(request, 'results/mitigationindex.html', context) 


def mitigation(request, consequence_id):   
    consequence = get_object_or_404(Consequence, pk=consequence_id)
    context = {'consequence': consequence}
    return render(request, 'results/mitigation.html', context) 


def detail(request, consequence_id):   
    consequence = get_object_or_404(Consequence, pk=consequence_id)
    context = {'consequence': consequence}
    return render(request, 'results/detail.html', context) 


def context(request, consequence_id):    
    consequence = get_object_or_404(Consequence, pk=consequence_id)
    context = {'consequence': consequence}
    return render(request, 'results/context.html', context) 


def missingdetail(request, missinginfo_id):
    missinginfo = get_object_or_404(MissingInfo, pk=missinginfo_id)
    context = {'missinginfo': missinginfo}
    return render(request, 'results/missingdetail.html', context)  


def manuallyaccept(request, missinginfo_id):
    missingData = get_object_or_404(MissingInfo, pk=missinginfo_id)
    
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ManuallyAcceptForm(request.POST)
        # check whether it's valid:
        if form.is_valid(): #processing
            # update ManualComments in Database 
            formcontent = form.cleaned_data
            for q in Consequence.objects.all():
                c = q.missinginfo_set.filter(missinginfo_text=missingData)
                # add manual comment, delete missing info
                if c:
                    print(c)
                    q.manualcomments_set.create(missinginfo_id = missinginfo_id, missinginfo_text=missingData, comments_text=formcontent['comments'], operator=formcontent['operator'], email=formcontent['email'], mod_date=timezone.now())
                    q.save()                    
                    # remove MissingInfo in Database
                    c.delete()
                    print (q)             
            #print(formcontent['comments']) 
            
            # redirect to a new URL:
            return HttpResponseRedirect('/results/')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = ManuallyAcceptForm()
 
    return render(request, 'results/manuallyaccept.html', {'form': form, 'missinginfo': missingData, 'method':request.method})



# to check the detail of manually accepted comments
def manualcommentsdetail(request, missinginfo_id):
    manualcomments = get_object_or_404(ManualComments, pk=missinginfo_id)
    context = {'manualcomments': manualcomments}
    return render(request, 'results/manualcommentsdetail.html', context) 


def addingdata(request, missinginfo_id):
    missingData = get_object_or_404(MissingInfo, pk=missinginfo_id) 
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AddingDataForm(request.POST)
        # check whether it's valid:
        if form.is_valid(): 
            # update ManualAddInfo in Database 
            formcontent = form.cleaned_data
            for q in Consequence.objects.all():
                c = q.missinginfo_set.filter(missinginfo_text=missingData)
                # add manual comment, delete missing info
                if c:
                    print(c)
                    q.manualaddinfo_set.create(missinginfo_id = missinginfo_id, missinginfo_text=missingData, data=formcontent['data'], operator=formcontent['operator'], email=formcontent['email'], mod_date=timezone.now())
                    q.save()                    
                    # remove MissingInfo in Database
                    c.delete()
                    print (q)             
            # redirect to a new URL:
            return HttpResponseRedirect('/results/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = AddingDataForm()
 
    return render(request, 'results/addingdata.html', {'form': form, 'missinginfo': missingData})
 

# to check the details of manually added missing data
def manualaddeddetail(request, missinginfo_id):
    print(missinginfo_id)
    manualaddeddata = get_object_or_404(ManualAddInfo, pk=missinginfo_id)
    context = {'manualaddeddata': manualaddeddata}
    return render(request, 'results/manualaddeddetail.html', context)  

results/templates/results/consequencelist.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 95%;
}

table td, table th {
    border: 1px solid #ddd;
    padding: 2px;
}

table tr:nth-child(even){background-color: #f2f2f2;}

table tr:hover {background-color: #ddd;}

table th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
}
br {
  content: " ";
  display: block;
  margin: 10px;
}
</style>
</head>
<body>
<b> <font size = "4", style="font-family: Trebuchet MS, Arial, Helvetica, sans-serif">You're looking at the Potential Consequence List view! </font></b>
<br/>   
     <table class="table table-bordered table-hover table-striped tablesorter">
<caption><b>Severity</b></caption>
<col width="250">
                <thead>
                <tr>                  
                  <th class="header"> Consequences (Hazards/Critical Conditions) <i class="icon-sort"></i></th>
                  <th class="header"> Missing Information/Facts  <i class="icon-sort"></i></th> 
                  <th class="header"> Manually Accepted Missing Facts <i class="icon-sort"></i></th>   
                  <th class="header"> Manually Added Missing Facts <i class="icon-sort"></i></th>                    
                  <th class="header"> Uncertainty/Likelihood <i class="icon-sort"></i></th>
                  <th class="header"> Severity <i class="icon-sort"></i></th>                 
                </tr>
            </thead>
            <tbody>

            {% for consequence in consequence_list %}
                <tr>                   
                    <td><a href="{% url 'results:context' consequence.id %}">{{ consequence.consequence_text }}</a></td>
                    <td> <ul>
{% for missinginfo in consequence.missinginfo_set.all %}
    <li><a href="{% url 'results:missingdetail' missinginfo.id %}">{{ missinginfo.missinginfo_text }}</a></li>{% endfor %} </ul>
</td>
                    <td> <ul>
{% for missinginfo in consequence.manualcomments_set.all %}
    <li><a href="{% url 'results:manualcommentsdetail' missinginfo.id %}">{{ missinginfo.missinginfo_text }}</a></li>{% endfor %} </ul>
</td>                  
                    <td> <ul>
{% for missinginfo in consequence.manualaddinfo_set.all %}
    <li><a href="{% url 'results:manualaddeddetail' missinginfo.id %}">{{ missinginfo.missinginfo_text }}</a></li>{% endfor %} </ul>
</td>                     
                    <td> <ul>
{% for likelihood in consequence.likelihood_set.all %}
    <p>{{ likelihood.likelihood_text }}</p>{% endfor %} </ul>
</td>
                    <td>  
{% for severity in consequence.severity_set.all %}
    <p>{{ severity.severity_text }}</p>{% endfor %}  
</td>
                </tr>
            {% endfor %}

            </tbody>
     </table>
 
<div style="position:relative; left:780px;top:30px;  ">
<button id="riskmatrixBtn" value="myvalue" onclick="location.href='/results'">Risk matrix view</button>
</div>

<div style="position:relative; left:980px;  ">
<button id="mitigationBtn" value="myvalue" onclick="location.href='/results/mitigationindex'">Mitigation view</button>
</div>

</body>
</html>
 

results/templates/results/context.html
<p> Reasoning context of {{ consequence.consequence_text}}</p>

results/templates/results/detail.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 95%;
}

table td, table th {
    border: 1px solid #ddd;
    padding: 2px;
}

table tr:nth-child(even){background-color: #f2f2f2;}

table tr:hover {background-color: #ddd;}

table th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
}
br {
  content: " ";
  display: block;
  margin: 10px;
}

</style>
</head>
<body>

<b> <font size = "4", style="font-family: Trebuchet MS, Arial, Helvetica, sans-serif">
You're looking at the detail of potential consequence {{consequence.consequence_text}}!
</font></b>

     <table class="table table-bordered table-hover table-striped tablesorter">
<caption><b>Potential Consequence</b></caption>
<br/>
                <thead>
                <tr>                  
                  <th class="header"> Consequences (Hazards/Critical Conditions) <i class="icon-sort"></i></th>
                  <th class="header"> Missing Information/Facts <i class="icon-sort"></i></th>           
                  <th class="header"> Manually Accepted Missing Facts <i class="icon-sort"></i></th>   
                  <th class="header"> Manually Added Missing Facts <i class="icon-sort"></i></th>             
                  <th class="header"> Uncertainty/Likelihood <i class="icon-sort"></i></th>
                  <th class="header"> Severity <i class="icon-sort"></i></th>                 
                </tr>
            </thead>
            <tbody>
 
                <tr>                   
                    <td><a href="{% url 'results:context' consequence.id %}">{{ consequence.consequence_text }}</a></td>
                    <td> <ul>
{% for missinginfo in consequence.missinginfo_set.all %}
    <li><a href="{% url 'results:missingdetail' missinginfo.id %}">{{ missinginfo.missinginfo_text }}</a></li>{% endfor %} </ul>
</td>
                    <td> <ul>
{% for missinginfo in consequence.manualcomments_set.all %}
    <li><a href="{% url 'results:manualcommentsdetail' missinginfo.id %}">{{ missinginfo.missinginfo_text }}</a></li>{% endfor %} </ul>
</td>                  
                    <td> <ul>
{% for missinginfo in consequence.manualaddinfo_set.all %}
    <li><a href="{% url 'results:manualaddeddetail' missinginfo.id %}">{{ missinginfo.missinginfo_text }}</a></li>{% endfor %} </ul>
</td>                                      
                    <td> <ul>
{% for likelihood in consequence.likelihood_set.all %}
    <p>{{ likelihood.likelihood_text }}</p>{% endfor %} </ul>
</td>
                    <td>  
{% for severity in consequence.severity_set.all %}
    <p>{{ severity.severity_text }}</p>{% endfor %}  
</td>
                </tr> 

            </tbody>
     </table>

<br/>
<b>Note:</b>
<ol>
<li> Please click Consequence <font size="2" color="red">(Cn)</font> for reasoning context;</li>
<li> Please click Missing Information <font size="2" color="red">(Fn)</font> for more instructions; </li>
<li> Please click Manually Accepted Facts for previous archive; </li>
<li> Please click Manually Added Missing Facts for previous archive. </li>

</ol>

</body>
</html>
 

results/templates/results/index (another copy).html
<!DOCTYPE html>
<html>
<head>
<style>
table {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 90%;
}

table td, table th {
    border: 1px solid #ddd;
    padding: 12px;
}

table tr:nth-child(even){background-color: #f2f2f2;}

table tr:hover {background-color: #ddd;}

table th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
}
br {
  content: " ";
  display: block;
  margin: 10px;
}

</style>
</head>
<body>

<b> <font size = "4", style="font-family: Trebuchet MS, Arial, Helvetica, sans-serif">You're looking at the Risk Matrix! </font></b>
<br/>  
     <table>
<caption><b>Severity</b></caption>
                <thead>
                <tr>
                  <th class="header">   <i class="icon-sort"></i></th>  
                  <th class="header">   <i class="icon-sort"></i></th>                
                  <th class="header"> Negotiable <i class="icon-sort"></i></th>
                  <th class="header"> Marginal <i class="icon-sort"></i></th>                     
                  <th class="header"> Critical <i class="icon-sort"></i></th>
                  <th class="header"> Catastrophic <i class="icon-sort"></i></th>                 
                </tr>
            </thead>
            <tbody>
                <tr> 
                    <td rowspan="4"><b>Likelihood</b></td>
                    <td> Definite  </td>                  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Negotiable" and likelihood.likelihood_text == "Definite"%}  {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %}<a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a> {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Marginal" and likelihood.likelihood_text == "Definite"%}  {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %}<a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a> {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>                  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Critical" and likelihood.likelihood_text == "Definite"%}  {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a> {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Catastrophic" and likelihood.likelihood_text == "Definite"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a> {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>  
                </tr>
                <tr> 
                    <td> Very Likely </td>                  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Negotiable" and likelihood.likelihood_text == "Very Likely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Marginal" and likelihood.likelihood_text == "Very Likely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>                  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Critical" and likelihood.likelihood_text == "Very Likely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Catastrophic" and likelihood.likelihood_text == "Very Likely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>
                </tr>
                <tr> 
                    <td> Likely </td>                  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Negotiable" and likelihood.likelihood_text == "Likely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Marginal" and likelihood.likelihood_text == "Likely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>                  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Critical" and likelihood.likelihood_text == "Likely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Catastrophic" and likelihood.likelihood_text == "Likely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>
                </tr>
                <tr> 
                    <td> Unlikely </td>                  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Negotiable" and likelihood.likelihood_text == "Unlikely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Marginal" and likelihood.likelihood_text == "Unlikely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>                  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Critical" and likelihood.likelihood_text == "Unlikely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>  
                    <td> {% for consequence in consequence_list %}
{% for severity in consequence.severity_set.all %}
{% for likelihood in consequence.likelihood_set.all %}
{% if severity.severity_text == "Catastrophic" and likelihood.likelihood_text == "Unlikely"%} {% if consequence.missinginfo_set.count == 0 %} <a href="{% url 'results:mitigation' consequence.id %}">{{ consequence.consequence_text }},
{% else %} <a href="{% url 'results:detail' consequence.id %}">{{ consequence.consequence_text }}<font size="2" color="red">(?{{consequence.missinginfo_set.count}})</font></a>, {% endif %}{% endif %}{% endfor %}{% endfor %}{% endfor %} </td>
                </tr>
            </tbody>
     </table>
<p>Note:</p>
<ol>
<li> <font size="2" color="red">(?n)</font> means the number of missing information, please click for more details.</li>
<li> For consequences without (?n), click for mitigation measures. </li>
</ol>


<button id="mitigationBtn" value="myvalue" onclick="location.href='/results/mitigationindex'">Mitigation view</button>

</body>
</html>
 